### ISSUE TITLE
Crash with PAE2, Missing GUI Textures in Stocker Terminal

### ISSUE THREAD

**Issue by minimalistjack** [solidDoWant/GregTech-Energistics#7]
Hey there, just installed this mod into Omnifactory Dev edition. While I was testing before adding it to my server the stocker terminal had missing textures (not mod breaking just wanted to point out), but the main issue at hand was I added one of the AE2 stocker covers all fine, but when placing a pattern inside the terminal it crashes. Attached is the crash log.

[crash-2021-08-10_13.34.26-client.txt](https://github.com/solidDoWant/GregTech-Energistics/files/6958792/crash-2021-08-10_13.34.26-client.txt)

**Comment by minimalistjack** [comment]
Heres the pastebin if its easier:
https://pastebin.com/q4rm7QFj

**Comment by magcicada** [comment]
You can compile [#6](https://github.com/solidDoWant/GregTech-Energistics/pull/6)  yourself to resolve the crash, and the missing texture you can resolve as [#3](https://github.com/solidDoWant/GregTech-Energistics/pull/3) .

**Comment by magcicada** [comment]
You can close this issue.
